src: add default provider to store.c
This allows the correct error (the one that I'm troubleshooting to be
displayed) which is:
Error: error:16000069:STORE routines::unregistered scheme